SkullStripping part
cpp-lln-lab/CPP_SPM pull request #188
Opened 2020-11-17 12:36 UTC by anege

2020-11-17 12:41 UTC, Remi-Gau commented
Cool !

Thanks @anege !

I will have a look a bit later and give you some feedback on this!

2020-11-17 18:08 UTC, marcobarilari requested changes
Hi Ane, thank you very much. I just had a very quick look at it, I tempted to propose to keep this PR open so that we can fill in the missing part before merging it.

2020-11-29 16:20 UTC, Remi-Gau requested changes
Super late to review this.

Sorry @anege 

Couple of minor changes and things to fix. If you don't have time to look at it I can take over. :-)

2020-11-29 16:20 UTC, Remi-Gau commented on src/batches/setBatchCoregistration.m
> +  % Set the batch for corregistering the source images into the reference image???
```suggestion
  % Set the batch for coregistering the source images into the reference image
```

2020-11-29 16:20 UTC, Remi-Gau commented on src/batches/setBatchCoregistrationFmap.m
> +  % Set the batch for the coregistration of functional maps
```suggestion
  % Set the batch for the coregistration of field maps
```

2020-11-29 16:20 UTC, Remi-Gau commented on src/batches/setBatchReslice.m
> +function matlabbatch = setBatchReslice(matlabbatch, ref, src)
```suggestion
function matlabbatch = setBatchReslice(matlabbatch, referenceImg, sourceImages)
```

2020-11-29 16:20 UTC, Remi-Gau commented on src/batches/setBatchReslice.m
> +function matlabbatch = setBatchReslice(matlabbatch, ref, src)
indeed

2020-11-29 16:20 UTC, Remi-Gau commented on src/batches/setBatchReslice.m
> +  % :type ref: string
```suggestion
  % :param referenceImg: Reference image
  % :type referenceImg: string
```

2020-11-29 16:20 UTC, Remi-Gau commented on src/batches/setBatchReslice.m
> +  % :type src: cell
```suggestion
  % :param sourceImages: Source images
  % :type sourceImages: cell
```

2020-11-30 13:59 UTC, anege commented
What do I have to do?
Since you already suggested some changes, I just approved those changes by clicking "commit sugestion"...and I received a lot of "run failed" mails...
________________________________
De: Remi Gau <notifications@github.com>
Enviado: domingo, 29 de noviembre de 2020 17:21
Para: cpp-lln-lab/CPP_SPM <CPP_SPM@noreply.github.com>
Cc: Ane Gurtubay Antolin <ane.gurtubay@uclouvain.be>; Mention <mention@noreply.github.com>
Asunto: Re: [cpp-lln-lab/CPP_SPM] SkullStripping part (#188)


@Remi-Gau requested changes on this pull request.

Super late to review this.

Sorry @anege<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fanege&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685712219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HWrkP0nRvARdXnXAsnVJiVxPBZMNzXpPawRoF4Yi%2Bow%3D&reserved=0>

Couple of minor changes and things to fix. If you don't have time to look at it I can take over. :-)

________________________________

In src/batches/setBatchCoregistration.m<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23discussion_r532230809&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685722214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nWQbdhohjUDlHj5ZIzhr%2FCDs4kd283B4109EwjxJX%2FY%3D&reserved=0>:

> @@ -2,28 +2,25 @@



 function matlabbatch = setBatchCoregistration(matlabbatch, ref, src, other)

   %

-  % Short description of what the function does goes here.

+  % Set the batch for corregistering the source images into the reference image???



⬇️ Suggested change

-  % Set the batch for corregistering the source images into the reference image???

+  % Set the batch for coregistering the source images into the reference image



________________________________

In src/batches/setBatchCoregistrationFmap.m<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23discussion_r532230919&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685732205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kUnxi2ZTdb2ZwCF%2BHSe7PsbAtQiXyeohncFDDXAXXbU%3D&reserved=0>:

> @@ -2,20 +2,21 @@



 function matlabbatch = setBatchCoregistrationFmap(BIDS, opt, subID)

   %

-  % Short description of what the function does goes here.

+  % Set the batch for the coregistration of functional maps



⬇️ Suggested change

-  % Set the batch for the coregistration of functional maps

+  % Set the batch for the coregistration of field maps



________________________________

In src/batches/setBatchReslice.m<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23discussion_r532231061&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685732205%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2B9e0%2FaqD%2BYsIIqVNsyKqcNQqAQ0IOOPePU8O4BLVS0%3D&reserved=0>:

> @@ -1,29 +1,24 @@

 % (C) Copyright 2020 CPP BIDS SPM-pipeline developers



-function matlabbatch = setBatchReslice(matlabbatch, referenceImg, sourceImages)

+function matlabbatch = setBatchReslice(matlabbatch, ref, src)



⬇️ Suggested change

-function matlabbatch = setBatchReslice(matlabbatch, ref, src)

+function matlabbatch = setBatchReslice(matlabbatch, referenceImg, sourceImages)



________________________________

In src/batches/setBatchReslice.m<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23discussion_r532231135&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685742203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=INV8iq1NQAnou%2FfolFQ2U4xsrXvLYOAZ0vyA%2FB9qNhk%3D&reserved=0>:

> +  % :param ref: Reference image

+  % :type ref: string



⬇️ Suggested change

-  % :param ref: Reference image

-  % :type ref: string

+  % :param referenceImg: Reference image

+  % :type referenceImg: string



________________________________

In src/batches/setBatchReslice.m<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23discussion_r532231165&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685742203%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zPOvV4dsUgNshyX4qiTMtU7VWJbxYi6Zi8KUw56bMG0%3D&reserved=0>:

> +  % :param src: Source images

+  % :type src: cell



⬇️ Suggested change

-  % :param src: Source images

-  % :type src: cell

+  % :param sourceImages: Source images

+  % :type sourceImages: cell



________________________________

In src/batches/setBatchReslice.m<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23discussion_r532231079&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685752197%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=igVaZywFBdm7IJdisnL4PMEOYSRw%2BnxKq8%2BNZ3tyOfI%3D&reserved=0>:

> @@ -1,29 +1,24 @@

 % (C) Copyright 2020 CPP BIDS SPM-pipeline developers



-function matlabbatch = setBatchReslice(matlabbatch, referenceImg, sourceImages)

+function matlabbatch = setBatchReslice(matlabbatch, ref, src)



indeed

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcpp-lln-lab%2FCPP_SPM%2Fpull%2F188%23pullrequestreview-540493872&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685762195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=etqFlwnnovfHmwz3bnNcQ2XnQlwUeLDuA5M3PbbD%2B9Q%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAL74OK5O6IWUYDMD3Y6U3S3SSJYHDANCNFSM4TYQL3TQ&data=04%7C01%7Cane.gurtubay%40uclouvain.be%7C38c8e668034a4354e2d608d89482c6fb%7C7ab090d4fa2e4ecfbc7c4127b4d582ec%7C0%7C0%7C637422636685762195%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=TpcSHc8pp13FU6UrxZmU28hbAEuCJleEb3qXeqIAdBE%3D&reserved=0>.

2020-11-30 20:13 UTC, marcobarilari commented
@anege receiving so many emails telling you are failing is not helpfulf for self-esteem. As Dante says: "Don't care about them, just look and go on." 

Don't worry about them, we will fix all those fails the time we will merge the branch `doc` into `dev`

2020-12-07 06:57 UTC, Remi-Gau approved these changes
This looks good for merge to me. :-)

2020-12-07 06:58 UTC, Remi-Gau commented
> What do I have to do? Since you already suggested some changes, I just approved those changes by clicking "commit sugestion"...and I received a lot of "run failed" mails...

Hey @anege 

Yeah I agree that some of those warning emails can be a bit scary. I will try to explain that tomorrow in the github lab tour.

2020-12-07 06:58 UTC, merged